varying vec2 textureCoordinate; uniform sampler2D userTexture; uniform sampler2D offsetTexture; uniform highp vec2 size_source; uniform highp float boundaryFreeze; 
#if defined FLOATTOBYTE
 uniform highp float floatFactor; 
#endif
 vec4 CatmullRomResample(sampler2D tex, vec2 uv) { vec2 samplePos = uv * size_source; vec2 texPos1 = floor(samplePos - 0.5) + 0.5; vec2 texFloor = samplePos - texPos1; vec2 w0 = texFloor * (-0.5 + texFloor * (1.0 - 0.5 * texFloor)); vec2 w1 = 1.0 + texFloor * texFloor * (-2.5 + 1.5 * texFloor); vec2 w2 = texFloor * (0.5 + texFloor * (2.0 - 1.5 * texFloor)); vec2 w3 = texFloor * texFloor * (-0.5 + 0.5 * texFloor); vec2 w12 = w1 + w2; vec2 offset12 = w2; if (w12.x > 1e-6) { offset12.x = w2.x / w12.x; } if (w12.y > 1e-6) { offset12.y = w2.y / w12.y; } vec2 texPos0 = texPos1 - vec2(1.0); vec2 texPos3 = texPos1 + vec2(2.0); vec2 texPos12 = texPos1 + offset12; texPos0 /= size_source; texPos3 /= size_source; texPos12 /= size_source; vec4 result = vec4(0.0); result += texture2D(tex, vec2(texPos0.x, texPos0.y)) * w0.x * w0.y; result += texture2D(tex, vec2(texPos12.x, texPos0.y)) * w12.x * w0.y; result += texture2D(tex, vec2(texPos3.x, texPos0.y)) * w3.x * w0.y; result += texture2D(tex, vec2(texPos0.x, texPos12.y)) * w0.x * w12.y; result += texture2D(tex, vec2(texPos12.x, texPos12.y)) * w12.x * w12.y; result += texture2D(tex, vec2(texPos3.x, texPos12.y)) * w3.x * w12.y; result += texture2D(tex, vec2(texPos0.x, texPos3.y)) * w0.x * w3.y; result += texture2D(tex, vec2(texPos12.x, texPos3.y)) * w12.x * w3.y; result += texture2D(tex, vec2(texPos3.x, texPos3.y)) * w3.x * w3.y; return result; } void main() { highp vec4 offsetValue = texture2D(offsetTexture, textureCoordinate); highp vec2 offset = vec2(0.0); 
#if defined FLOATTOBYTE
 highp float invFloatFactor = 1.0 / floatFactor; offset.x = invFloatFactor * (offsetValue.r + offsetValue.g / 255.0 - 0.498); offset.y = invFloatFactor * (offsetValue.b + offsetValue.a / 255.0 - 0.498); 
#else
 offset = offsetValue.xy; 
#endif
 highp vec2 finalCoord = textureCoordinate + offset; vec4 endcolor = vec4(0.0); if (length(offset) > 0.0001) { if (boundaryFreeze > 0.5) { endcolor = CatmullRomResample(userTexture, finalCoord); } else { if (finalCoord.x < 0.0 || finalCoord.x > 1.0 || finalCoord.y < 0.0 || finalCoord.y > 1.0) { endcolor = vec4(0.0); } else { endcolor = CatmullRomResample(userTexture, finalCoord); } } } else { endcolor = texture2D(userTexture, finalCoord); } gl_FragColor = endcolor; }