uniform sampler2D inputImageTexture; uniform sampler2D inputImageTexture2; uniform sampler2D inputImageTexture3; varying highp vec2 textureCoordinate; varying highp vec2 textureCoordinateCrop; uniform sampler2D laughLineMaskTexture; uniform sampler2D skinMaskTexture; uniform sampler2D acneCleanMaskTexture; uniform sampler2D nevusMaskTexture; uniform lowp float tearTroughAlpha; uniform lowp float faceSmoothAlpha; uniform lowp float faceColorAlphaGreen; uniform lowp float faceColorAlphaRed; uniform lowp float faceColorAlpha; uniform lowp float laughLineNewAlpha; uniform lowp float isOnlyRemoveShadow; uniform lowp float levelRedGreen; uniform lowp float fAverageLuma; uniform lowp float fAverageRed; uniform lowp float fAverageRatioRed; uniform lowp float flawSmoothAlpha; 
#ifdef WITH_JOWLBRIGHT 
 uniform sampler2D archFillerMaskTexture; uniform lowp float jowlFillAlpha; uniform lowp vec2 center1; uniform lowp vec2 center2; uniform lowp vec2 attenuation; lowp float isLeft(vec2 v12, vec2 v13) { float crossProduct = v12.x * v13.y - v12.y * v13.x; return step(0.0, crossProduct); } 
#endif 
 void main() { lowp vec4 iColor = texture2D(inputImageTexture, textureCoordinate); lowp float skinMask = texture2D(skinMaskTexture, textureCoordinate).r; lowp vec3 color = iColor.rgb; lowp vec3 lowColor = texture2D(inputImageTexture3, textureCoordinateCrop).rgb; lowp vec3 highColor = color - lowColor; lowp vec3 gaussColor = texture2D(inputImageTexture2, textureCoordinateCrop).rgb; lowp float faceSmooth = texture2D(acneCleanMaskTexture, textureCoordinate).b; lowp vec3 laughLineMask = texture2D(laughLineMaskTexture, textureCoordinate).rgb; lowp float alpha = max(max(tearTroughAlpha * laughLineMask.r, laughLineNewAlpha * laughLineMask.b), faceSmooth * faceSmoothAlpha); 
#ifdef WITH_JOWLBRIGHT 
 lowp float archFillerMaskColor = texture2D(archFillerMaskTexture, textureCoordinate).b; lowp float fIsLeft = isLeft(center2-center1, textureCoordinate.xy - center1); lowp float smoothJowl = jowlFillAlpha*mix(attenuation.y, attenuation.x, fIsLeft); alpha = max(alpha, archFillerMaskColor*smoothJowl); 
#endif 
 lowp float diff = clamp(15.0 * (gaussColor.r - lowColor.r) + 1.0, 0.0, 1.0); alpha = mix(alpha, alpha * diff, isOnlyRemoveShadow); color = mix(lowColor, gaussColor, alpha); lowp vec3 newColor; 
#ifdef FACE_COLOR_BALANCE 
 newColor = color; if(color.b < fAverageLuma){ highp float changed_b = color.b / fAverageLuma; highp float new_b = 1.0 - (changed_b - 1.0) * (changed_b - 1.0); new_b = new_b * fAverageLuma - color.b; mediump float ratio = (color.b + new_b) / color.b; newColor.b += new_b; mediump float new_g = color.g * ratio - color.g; new_g = min(new_g, new_b); newColor.g += new_g; newColor.r += new_g; lowp float alpha_dark = clamp(1.0 + 15.0 * (gaussColor.r - lowColor.r), 0.0, 1.0); lowp float alpha_luma = clamp(1.0 + (color.b - 0.4) * 2.0, 0.0, 1.0); lowp float alpha_mix = faceColorAlpha * laughLineMask.g; 
#ifdef WITH_JOWLBRIGHT 
 alpha_mix = max(alpha_mix, archFillerMaskColor*smoothJowl); 
#endif 
 color = mix(color, newColor, alpha_mix * alpha_dark * alpha_luma); } if(iColor.r - iColor.g < levelRedGreen) { newColor = color; lowp float delta = levelRedGreen - (iColor.r - iColor.g); mediump vec2 s; newColor.g = mix(color.g, color.g - delta, laughLineMask.g); newColor.b = color.b + (newColor.g - color.g); s.x = clamp(1.0 + (color.b - 0.5) * 4.0, 0.0, 1.0); s.y = clamp(1.0 + (fAverageRatioRed - iColor.b / (iColor.r + 0.001)) * 10.0, 0.0, 1.0); color = mix(color, newColor, min(1.0, min(s.x,s.y)) * faceColorAlphaGreen); } 
#endif 
 
#ifdef FACE_COLOR_BALANCE_RED 
 newColor = color; float ratio = max(color.b, color.g) / (color.r + 0.001); float levelblack = max(max(gaussColor.b, gaussColor.g) / (gaussColor.r + 0.001), fAverageRatioRed); levelblack *= (1.0 + min(max(fAverageRed - 0.1, 0.0), 0.1)); if(ratio < levelblack) { vec3 newColor1 = color; newColor1.r = gaussColor.r; vec3 newColor2 = color; newColor2.b = max(newColor2.b, gaussColor.b); newColor2.g = max(newColor2.g, gaussColor.g); newColor2.r = max(newColor2.b, newColor2.g) / levelblack; if(color.b < c